# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/liteDRAM.xdc

# XDC: imports/src/rvfpga.xdc

# Block Designs: bd/BD/BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD || ORIG_REF_NAME==BD} -quiet] -quiet

# IP: bd/BD/ip/BD_swerv_wrapper_verilog_0_0/BD_swerv_wrapper_verilog_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_swerv_wrapper_verilog_0_0 || ORIG_REF_NAME==BD_swerv_wrapper_verilog_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_intcon_wrapper_bd_0_0/BD_intcon_wrapper_bd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_intcon_wrapper_bd_0_0 || ORIG_REF_NAME==BD_intcon_wrapper_bd_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bootrom_wrapper_0_0/BD_bootrom_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bootrom_wrapper_0_0 || ORIG_REF_NAME==BD_bootrom_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_gpio_wrapper_0_0/BD_gpio_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_gpio_wrapper_0_0 || ORIG_REF_NAME==BD_gpio_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_syscon_wrapper_0_0/BD_syscon_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_syscon_wrapper_0_0 || ORIG_REF_NAME==BD_syscon_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_0/BD_bidirec_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_0 || ORIG_REF_NAME==BD_bidirec_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_6/BD_bidirec_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_6 || ORIG_REF_NAME==BD_bidirec_0_6} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_7/BD_bidirec_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_7 || ORIG_REF_NAME==BD_bidirec_0_7} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_1_4/BD_bidirec_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_1_4 || ORIG_REF_NAME==BD_bidirec_1_4} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_8/BD_bidirec_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_8 || ORIG_REF_NAME==BD_bidirec_0_8} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_1_5/BD_bidirec_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_1_5 || ORIG_REF_NAME==BD_bidirec_1_5} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_3/BD_bidirec_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_2_3 || ORIG_REF_NAME==BD_bidirec_2_3} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_3_3/BD_bidirec_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_3_3 || ORIG_REF_NAME==BD_bidirec_3_3} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_9/BD_bidirec_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_9 || ORIG_REF_NAME==BD_bidirec_0_9} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_1_6/BD_bidirec_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_1_6 || ORIG_REF_NAME==BD_bidirec_1_6} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_4/BD_bidirec_2_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_2_4 || ORIG_REF_NAME==BD_bidirec_2_4} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_3_4/BD_bidirec_3_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_3_4 || ORIG_REF_NAME==BD_bidirec_3_4} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_4_2/BD_bidirec_4_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_4_2 || ORIG_REF_NAME==BD_bidirec_4_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_5_2/BD_bidirec_5_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_5_2 || ORIG_REF_NAME==BD_bidirec_5_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_6_2/BD_bidirec_6_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_6_2 || ORIG_REF_NAME==BD_bidirec_6_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_7_2/BD_bidirec_7_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_7_2 || ORIG_REF_NAME==BD_bidirec_7_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_10/BD_bidirec_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_10 || ORIG_REF_NAME==BD_bidirec_0_10} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_1_7/BD_bidirec_1_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_1_7 || ORIG_REF_NAME==BD_bidirec_1_7} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_10_1/BD_bidirec_10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_10_1 || ORIG_REF_NAME==BD_bidirec_10_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_11_1/BD_bidirec_11_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_11_1 || ORIG_REF_NAME==BD_bidirec_11_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_12_1/BD_bidirec_12_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_12_1 || ORIG_REF_NAME==BD_bidirec_12_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_13_1/BD_bidirec_13_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_13_1 || ORIG_REF_NAME==BD_bidirec_13_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_14_1/BD_bidirec_14_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_14_1 || ORIG_REF_NAME==BD_bidirec_14_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_15_1/BD_bidirec_15_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_15_1 || ORIG_REF_NAME==BD_bidirec_15_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_5/BD_bidirec_2_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_2_5 || ORIG_REF_NAME==BD_bidirec_2_5} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_3_5/BD_bidirec_3_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_3_5 || ORIG_REF_NAME==BD_bidirec_3_5} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_4_3/BD_bidirec_4_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_4_3 || ORIG_REF_NAME==BD_bidirec_4_3} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_5_3/BD_bidirec_5_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_5_3 || ORIG_REF_NAME==BD_bidirec_5_3} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_6_3/BD_bidirec_6_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_6_3 || ORIG_REF_NAME==BD_bidirec_6_3} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_7_3/BD_bidirec_7_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_7_3 || ORIG_REF_NAME==BD_bidirec_7_3} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_8_1/BD_bidirec_8_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_8_1 || ORIG_REF_NAME==BD_bidirec_8_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_9_1/BD_bidirec_9_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_9_1 || ORIG_REF_NAME==BD_bidirec_9_1} -quiet] -quiet

# XDC: bd/BD/BD_ooc.xdc
